app_info_response_case ="Default"

[environment]
debug = "false"

[http]
port = "8080"
url_prefix = "/sse"
allowed_origin = "http://ensure_this_is_set.com"

[logging]
level = "INFO"
correlation_id_http_header = "x-correlation-id"