[package]
name = "broker-protobufs"
version = "0.1.0"
authors = ["kahgeh <kahgeh@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic="0.5.0"
prost="0.8.0"

[build-dependencies]
tonic-build = "0.5.1"