apiVersion: v1
kind: Service
metadata:
  name: client-register
  labels:
    app: client-register
spec:
  ports:
    - port: 6379
      protocol: TCP
  clusterIP: None
  selector:
    app: client-register
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-register
  labels:
    app: client-register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-register
  template:
    metadata:
      labels:
        app: client-register
    spec:
      containers:
        - name: client-register
          image: redis
