apiVersion: v1
kind: Service
metadata:
  name: sse-server
  labels:
    app: sse-server
spec:
  ports:
  - port: 80
    protocol: TCP
  clusterIP: None
  selector:
    app: sse-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-server
  labels:
    app: sse-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-server
  template:
    metadata:
      labels:
        app: sse-server
    spec:
      containers:
      - name: sse-server
        image: sse-server
