app_info_response_case = "Default"

[environment]
debug = "false"

[http]
port = "8081"
url_prefix = "/sse"
allowed_origin = "ignored"

[grpc]
port="50052"

[logging]
level = "INFO"
correlation_id_http_header = "x-correlation-id"

[outgoing_endpoints]
redis="redis://client-register/"

[readiness]
check="false"
retry_count="6"
retry_interval_in_seconds="5"